"""Branded PDF report generator for InfraScan AI Premium analyses."""

import re
from datetime import UTC, datetime
from pathlib import Path

from fpdf import FPDF

_FONTS_DIR = Path(__file__).parent.parent.parent / "assets" / "fonts"
_FONT_REG = str(_FONTS_DIR / "DejaVuSans.ttf")
_FONT_BOLD = str(_FONTS_DIR / "DejaVuSans-Bold.ttf")

_ACCENT = (0, 122, 255)  # InfraScan blue
_TEXT = (30, 30, 30)
_MUTED = (120, 120, 120)
_RULE = (220, 220, 220)
_BG_RISK = {
    "высокий": (255, 80, 80),
    "средний": (255, 165, 0),
    "низкий": (50, 200, 100),
    "high": (255, 80, 80),
    "medium": (255, 165, 0),
    "low": (50, 200, 100),
}
_WHITE = (255, 255, 255)


def _detect_risk(text: str) -> tuple[str, tuple]:
    """Extract risk level keyword from analysis text for color coding."""
    low = text.lower()
    for kw, color in _BG_RISK.items():
        if kw in low:
            return kw.upper(), color
    return "—", _MUTED


def _strip_markdown(text: str) -> str:
    """Remove markdown and emoji that DejaVu can't render."""
    text = re.sub(r"\*\*(.*?)\*\*", r"\1", text)
    text = re.sub(r"\*(.*?)\*", r"\1", text)
    text = re.sub(r"#{1,6}\s*", "", text)
    text = re.sub(r"`{1,3}", "", text)
    # Strip emoji and supplementary Unicode planes (not in DejaVu)
    text = re.sub(r"[\U00010000-\U0010FFFF]", "", text)
    # Strip most Miscellaneous Symbols block except common ones
    text = re.sub(r"[☀-⛿✀-➿]", "", text)
    return text


class _Report(FPDF):
    def __init__(self, locale: str = "ru"):
        super().__init__()
        self._locale = locale
        self.add_font("dj", "", _FONT_REG, uni=True)
        self.add_font("dj", "B", _FONT_BOLD, uni=True)

    # ── Header ────────────────────────────────────────────────────────────────
    def header(self) -> None:
        # Blue bar at top
        self.set_fill_color(*_ACCENT)
        self.rect(0, 0, 210, 14, "F")
        self.set_font("dj", "B", 11)
        self.set_text_color(*_WHITE)
        self.set_y(3)
        self.cell(
            0,
            8,
            "InfraScan AI  ·  Нейро-Диагностика"
            if self._locale == "ru"
            else "InfraScan AI  ·  AI Diagnostics",
            align="C",
        )
        self.ln(14)

    # ── Footer ────────────────────────────────────────────────────────────────
    def footer(self) -> None:
        self.set_y(-14)
        self.set_draw_color(*_RULE)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(2)
        self.set_font("dj", "", 7)
        self.set_text_color(*_MUTED)
        label = "Сгенерировано" if self._locale == "ru" else "Generated by"
        self.cell(
            0,
            5,
            f"{label}: InfraScan AI  |  infrascan-ai.ru  |  Powered by Gemini Vision",
            align="C",
        )

    # ── Section helpers ───────────────────────────────────────────────────────
    def h_rule(self) -> None:
        self.set_draw_color(*_RULE)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(3)

    def section_title(self, title: str) -> None:
        self.set_font("dj", "B", 10)
        self.set_text_color(*_ACCENT)
        self.cell(0, 7, title)
        self.ln(7)
        self.set_text_color(*_TEXT)

    def body_text(self, text: str) -> None:
        self.set_font("dj", "", 9.5)
        self.set_text_color(*_TEXT)
        self.multi_cell(0, 5.5, text)
        self.ln(2)


def generate_report(analysis_text: str, locale: str = "ru", analysis: dict | None = None) -> bytes:
    """Return a branded PDF bytes object for the given analysis text."""
    pdf = _Report(locale)
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.add_page()
    pdf.set_left_margin(12)
    pdf.set_right_margin(12)

    now = datetime.now(UTC)
    date_str = now.strftime("%d.%m.%Y  %H:%M UTC")

    # ── Meta block ───────────────────────────────────────────────────────────
    title = "ОТЧЁТ О ТЕПЛОВИЗИОННОЙ ДИАГНОСТИКЕ" if locale == "ru" else "THERMAL INSPECTION REPORT"
    pdf.set_font("dj", "B", 14)
    pdf.set_text_color(*_TEXT)
    pdf.cell(0, 8, title)
    pdf.ln(9)

    pdf.set_font("dj", "", 9)
    pdf.set_text_color(*_MUTED)
    pdf.cell(0, 5, f"{'Дата' if locale == 'ru' else 'Date'}: {date_str}")
    pdf.ln(7)
    pdf.h_rule()

    # ── Risk badge ───────────────────────────────────────────────────────────
    risk_label, risk_color = _detect_risk(analysis_text)
    if risk_label != "—":
        label = "УРОВЕНЬ РИСКА" if locale == "ru" else "RISK LEVEL"
        pdf.set_font("dj", "B", 9)
        pdf.set_text_color(*_MUTED)
        pdf.cell(35, 7, label + ":")
        pdf.set_fill_color(*risk_color)
        pdf.set_text_color(*_WHITE)
        pdf.set_font("dj", "B", 9)
        pdf.cell(32, 7, f"  {risk_label}  ", fill=True, border=0)
        pdf.ln(11)
        pdf.h_rule()

    # ── Problems table (if raw analysis dict available) ───────────────────────
    if analysis and analysis.get("problems"):
        section_title = "ВЫЯВЛЕННЫЕ ДЕФЕКТЫ" if locale == "ru" else "DETECTED ISSUES"
        pdf.section_title(section_title)
        sev_map = {
            "low": ("НИЗКАЯ", "LOW"),
            "medium": ("СРЕДНЯЯ", "MEDIUM"),
            "high": ("ВЫСОКАЯ", "HIGH"),
            "critical": ("КРИТИЧЕСКАЯ", "CRITICAL"),
        }
        for i, p in enumerate(analysis["problems"][:8], 1):
            sev_key = p.get("severity", "medium")
            sev_ru, sev_en = sev_map.get(sev_key, ("—", "—"))
            sev_label = sev_ru if locale == "ru" else sev_en
            sev_color = _BG_RISK.get(sev_key, _MUTED)
            loc = _strip_markdown(p.get("location", "—"))
            desc = _strip_markdown(p.get("description", ""))

            pdf.set_font("dj", "B", 9)
            pdf.set_text_color(*_TEXT)
            pdf.cell(8, 6, f"{i}.")
            pdf.set_fill_color(*sev_color)
            pdf.set_text_color(*_WHITE)
            pdf.cell(26, 6, f" {sev_label} ", fill=True)
            pdf.set_text_color(*_MUTED)
            pdf.set_font("dj", "", 9)
            pdf.cell(0, 6, f"  {loc}")
            pdf.ln(7)
            if desc:
                pdf.set_font("dj", "", 8.5)
                pdf.set_text_color(*_TEXT)
                pdf.set_x(20)
                pdf.multi_cell(0, 5, desc)
                pdf.ln(1)
        pdf.h_rule()

    # ── Recommendations (if available) ───────────────────────────────────────
    if analysis and analysis.get("recommendations_detailed"):
        rec_title = "ПЛАН УСТРАНЕНИЯ" if locale == "ru" else "ACTION PLAN"
        pdf.section_title(rec_title)
        for step in analysis["recommendations_detailed"][:5]:
            pdf.set_font("dj", "", 9)
            pdf.set_text_color(*_TEXT)
            pdf.multi_cell(0, 5.5, _strip_markdown(f"• {step}"))
            pdf.ln(1)
        pdf.h_rule()

    # ── Analysis body ─────────────────────────────────────────────────────────
    section = "ПОЛНЫЙ ТЕКСТ АНАЛИЗА" if locale == "ru" else "FULL ANALYSIS"
    pdf.section_title(section)
    clean_text = _strip_markdown(analysis_text)
    pdf.body_text(clean_text)
    pdf.h_rule()

    # ── Disclaimer ────────────────────────────────────────────────────────────
    disclaimer = (
        "Данный отчёт сгенерирован ИИ на основе предоставленного фотоматериала. "
        "Для подтверждения результатов рекомендуется профессиональная тепловизионная диагностика."
        if locale == "ru"
        else "This report was generated by AI based on the provided photo. "
        "Professional thermal inspection is recommended for confirmation."
    )
    pdf.set_font("dj", "", 8)
    pdf.set_text_color(*_MUTED)
    pdf.multi_cell(0, 5, disclaimer)

    return bytes(pdf.output())
